name: Java CI with OpenGL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install dependencies
        run: sudo apt-get install -y libxrender1 libxtst6 libxi6 libgl1-mesa-dev xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          sleep 3 # 等待 Xvfb 启动
          echo $DISPLAY
          xdpyinfo -display :99

      - name: Enable debug mode
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Debug file system
        run: ls -R

      - name: Build and run tests
        run: ./gradlew lwjgl3:test --info --stacktrace

      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html
